-- Create Enums
CREATE TYPE student_status AS ENUM ('draft', 'pending_verification', 'rejected', 'awaiting_payment', 'payment_review', 'accepted');

-- Create Majors Table
CREATE TABLE majors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quota INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Majors
INSERT INTO majors (name, quota) VALUES
('Teknik Komputer & Jaringan', 100),
('Akuntansi', 100),
('Administrasi Perkantoran', 100);

-- Create Students Table (Standalone, No Auth dependency)
CREATE TABLE students (
  id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL, -- Used for login/lookup
  nisn TEXT UNIQUE NOT NULL,
  phone TEXT NOT NULL,
  
  gender TEXT,
  dob DATE,
  address TEXT,
  school_origin TEXT,
  graduation_year INTEGER,
  average_score NUMERIC(5,2),
  selected_major_id BIGINT REFERENCES majors(id),
  
  status student_status DEFAULT 'pending_verification'::student_status,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Payments Table
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  proof_image_url TEXT,
  status TEXT DEFAULT 'pending',
  admin_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Enable RLS (and allow Public Access)
ALTER TABLE majors ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Public Policies
CREATE POLICY "Public full access to majors" ON majors FOR ALL USING (true);
CREATE POLICY "Public full access to students" ON students FOR ALL USING (true);
CREATE POLICY "Public full access to payments" ON payments FOR ALL USING (true);
