-- Create Enums
CREATE TYPE app_role AS ENUM ('admin', 'student');
CREATE TYPE student_status AS ENUM ('draft', 'pending_verification', 'rejected', 'awaiting_payment', 'payment_review', 'accepted');

-- Create Majors Table
CREATE TABLE majors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  quota INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Seed Majors
INSERT INTO majors (name, quota) VALUES
('Teknik Komputer & Jaringan', 100),
('Akuntansi', 100),
('Administrasi Perkantoran', 100);

-- Create Custom Users Table (Extends Auth)
-- Note: We will use a trigger to automatically create a user entry here when a new auth user signs up
CREATE TABLE users (
  id UUID REFERENCES auth.users NOT NULL PRIMARY KEY,
  full_name TEXT,
  email TEXT,
  role app_role DEFAULT 'student'::app_role,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Students Table
CREATE TABLE students (
  id UUID REFERENCES users(id) ON DELETE CASCADE NOT NULL PRIMARY KEY,
  nisn TEXT UNIQUE,
  phone TEXT,
  gender TEXT,
  dob DATE,
  address TEXT,
  school_origin TEXT,
  graduation_year INTEGER,
  average_score NUMERIC(5,2),
  selected_major_id BIGINT REFERENCES majors(id),
  status student_status DEFAULT 'draft'::student_status,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- Create Payments Table
CREATE TABLE payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id UUID REFERENCES students(id) ON DELETE CASCADE NOT NULL,
  amount NUMERIC(12, 2) NOT NULL,
  proof_image_url TEXT,
  status TEXT DEFAULT 'pending', -- pending, confirmed, rejected
  admin_note TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- RLS Policies

-- Enable RLS
ALTER TABLE users ENABLE ROW LEVEL SECURITY;
ALTER TABLE majors ENABLE ROW LEVEL SECURITY;
ALTER TABLE students ENABLE ROW LEVEL SECURITY;
ALTER TABLE payments ENABLE ROW LEVEL SECURITY;

-- Users Policies
CREATE POLICY "Users can view their own profile" ON users
  FOR SELECT USING (auth.uid() = id);

CREATE POLICY "Admins can view all users" ON users
  FOR SELECT USING (
    EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin')
  );

-- Majors Policies (Public Read)
CREATE POLICY "Majors are viewable by everyone" ON majors
  FOR SELECT USING (true);

-- Students Policies
CREATE POLICY "Students can view and update their own data" ON students
  FOR ALL USING (auth.uid() = id);

CREATE POLICY "Admins can view and update all students" ON students
  FOR ALL USING (
    EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin')
  );

-- Payments Policies
CREATE POLICY "Students can view their own payments" ON payments
  FOR SELECT USING (
    auth.uid() = student_id
  );

CREATE POLICY "Students can insert their own payments" ON payments
  FOR INSERT WITH CHECK (
     student_id = auth.uid()
  );

CREATE POLICY "Admins can view and update all payments" ON payments
  FOR ALL USING (
    EXISTS (SELECT 1 FROM users WHERE id = auth.uid() AND role = 'admin')
  );

-- Function to handle new user signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER AS $$
BEGIN
  INSERT INTO public.users (id, full_name, email, role)
  VALUES (
    new.id, 
    new.raw_user_meta_data->>'full_name', 
    new.email, 
    COALESCE((new.raw_user_meta_data->>'role')::app_role, 'student')
  );
  
  -- If role is student, create student entry too (or wait for first login/registration step? Let's create it for NISN storage)
  IF (COALESCE((new.raw_user_meta_data->>'role')::app_role, 'student') = 'student') THEN
      INSERT INTO public.students (id, nisn, phone) 
      VALUES (
        new.id,
        new.raw_user_meta_data->>'nisn',
        new.raw_user_meta_data->>'phone'
      );
  END IF;

  RETURN new;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER;

-- Trigger the function on new user signup
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE PROCEDURE public.handle_new_user();